app = "estrading-machine-api"
primary_region = "sin"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "2s"
  path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
